import org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest

plugins {
    kotlin("multiplatform")
}

// The ZenWave language server for JavaScript runtimes, published as the npm package @zenwave360/lsp-js.
//
// Kotlin compiles the server (src/jsMain) to ES modules. The npm project in ./npm bundles them with
// vscode-languageserver into two self-contained entry points and assembles the package:
//   dist/node/zenwave-lsp-server.js    Node child process, speaking LSP over IPC (vscode-languageserver/node)
//   dist/browser/zenwave-lsp-worker.js Web Worker, speaking LSP over postMessage (vscode-languageserver/browser)
// Both entry points are verified over their real wire as part of `check`:
//   nodeIpcTest    forks the Node entry point and talks to it over IPC (npm/test)
//   jsBrowserTest  loads the worker entry point in a Web Worker in headless Chromium (src/jsTest)

kotlin {
    js(IR) {
        nodejs {
            testTask {
                // The worker wire test needs a browser Web Worker.
                filter.excludeTestsMatching("io.zenwave360.lsp.js.WorkerWireTest")
                useMocha {
                    timeout = "30s"
                }
            }
        }
        // jsBrowserTest (part of check) runs the unit tests and the worker wire test in headless Chromium,
        // so a Node-only import reaching the worker fails the build here, not in a consumer.
        browser {
            testTask {
                useKarma {
                    useChromeHeadless()
                }
            }
        }
        binaries.executable()
        useEsModules()
    }

    sourceSets {
        val jsMain by getting {
            kotlin.srcDir(layout.buildDirectory.dir("generated/lspJsVersion/kotlin"))
            dependencies {
                implementation(projects.lspCore)
                implementation(kotlin("stdlib-js"))
            }
        }

        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
    }
}

val lspJsVersion = project.version.toString()

val generateLspJsVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/lspJsVersion/kotlin")
    inputs.property("version", lspJsVersion)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("io/zenwave360/lsp/js/LspJsVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package io.zenwave360.lsp.js
            |
            |/** Generated by the lsp-js Gradle build from the project version. */
            |const val LSP_JS_VERSION: String = "$lspJsVersion"
            |""".trimMargin()
        )
    }
}

tasks.matching { it.name == "compileKotlinJs" || it.name == "jsSourcesJar" }.configureEach {
    dependsOn(generateLspJsVersion)
}

val isWindows = System.getProperty("os.name").lowercase().contains("windows")
val npmCommand = if (isWindows) "npm.cmd" else "npm"
val npmProjectDir = layout.projectDirectory.dir("npm")
val kotlinProductionDir = layout.buildDirectory.dir("compileSync/js/main/productionExecutable/kotlin")
val npmPackageDir = layout.buildDirectory.dir("npm-package")
val npmPackDir = layout.buildDirectory.dir("npm-pack")

val lspJsNpmInstall by tasks.registering(Exec::class) {
    group = "npm"
    description = "Installs the bundler and vscode-languageserver for the lsp-js npm project."
    workingDir = npmProjectDir.asFile
    inputs.files(npmProjectDir.file("package.json"), npmProjectDir.file("package-lock.json"))
    outputs.dir(npmProjectDir.dir("node_modules"))
    commandLine(npmCommand, "ci", "--no-audit", "--no-fund")
}

val lspJsBundle by tasks.registering(Exec::class) {
    group = "npm"
    description = "Bundles the Node IPC and Web Worker entry points and assembles the @zenwave360/lsp-js package."
    dependsOn(lspJsNpmInstall, "jsProductionExecutableCompileSync")
    workingDir = npmProjectDir.asFile
    inputs.dir(kotlinProductionDir)
    inputs.dir(npmProjectDir.dir("src"))
    inputs.files(npmProjectDir.file("build.mjs"), layout.projectDirectory.file("README.md"))
    inputs.property("version", lspJsVersion)
    outputs.dir(npmPackageDir)
    commandLine(
        "node", "build.mjs",
        "--kotlin-dir", kotlinProductionDir.get().asFile.absolutePath,
        "--out", npmPackageDir.get().asFile.absolutePath,
        "--version", lspJsVersion,
        "--readme", layout.projectDirectory.file("README.md").asFile.absolutePath,
    )
}

val nodeIpcTest by tasks.registering(Exec::class) {
    group = "verification"
    description = "Forks the packaged Node entry point and exercises it over child-process IPC."
    dependsOn(lspJsBundle)
    workingDir = npmProjectDir.asFile
    inputs.dir(npmPackageDir)
    inputs.dir(npmProjectDir.dir("test"))
    outputs.upToDateWhen { false }
    environment("LSP_JS_PACKAGE_DIR", npmPackageDir.get().asFile.absolutePath)
    commandLine("node", "--test", "--test-reporter=spec", "test/node-ipc.test.mjs")
}

val lspJsNpmPack by tasks.registering(Exec::class) {
    group = "npm"
    description = "Packs @zenwave360/lsp-js into build/npm-pack (local use only; nothing is published)."
    dependsOn(lspJsBundle)
    workingDir = npmPackageDir.get().asFile
    inputs.dir(npmPackageDir)
    outputs.dir(npmPackDir)
    doFirst { npmPackDir.get().asFile.mkdirs() }
    commandLine(npmCommand, "pack", "--pack-destination", npmPackDir.get().asFile.absolutePath)
}

// The worker wire test loads the packaged worker entry point, served by Karma at /base/kotlin/lsp-js-package/.
tasks.named<ProcessResources>("jsTestProcessResources") {
    dependsOn(lspJsBundle)
    from(npmPackageDir) {
        include("dist/browser/**", "package.json")
        into("lsp-js-package")
    }
}

tasks.named("check") { dependsOn(nodeIpcTest) }
tasks.named("assemble") { dependsOn(lspJsBundle) }
